// Generated by HopperHarvest/generate_value_schema_library.py.
// Inputs: Apple's public RealityKitScripting registry + the shipped RCP3 catalog.
// Do not hand-edit property lists; regenerate them from the public schema dump.

public enum ScriptGraphValueSchema {
    public struct Property: Sendable, Hashable {
        public let name: String
        public let swiftType: String
        public let isOptional: Bool
    }

    public struct NodeSchema: Sendable, Hashable {
        public let module: String
        public let typeName: String
        public let properties: [Property]
    }

    public struct EnumAssociatedValue: Sendable, Hashable {
        public let name: String
        public let swiftType: String
    }

    public struct EnumCase: Sendable, Hashable {
        public let name: String
        public let associatedValues: [EnumAssociatedValue]
    }

    public struct EnumNodeSchema: Sendable, Hashable {
        public let module: String
        public let typeName: String
        public let cases: [EnumCase]
    }

    public static let breakNodes: [String: NodeSchema] = [
        "tm_break_animation_playback_controller": NodeSchema(
            module: "RealityKit", typeName: "AnimationPlaybackController", properties: [
                Property(name: "blendFactor", swiftType: "Swift.Float", isOptional: false),
                Property(name: "duration", swiftType: "Swift.Double", isOptional: false),
                Property(name: "entity", swiftType: "RealityKit.Entity", isOptional: true),
                Property(name: "isComplete", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isPaused", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isPlaying", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isStopped", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isValid", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Float", isOptional: false),
                Property(name: "time", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_break_audio_group_playback_controller": NodeSchema(
            module: "RealityKit", typeName: "AudioPlaybackGroupController", properties: [
                Property(name: "entities", swiftType: "Swift.Array<RealityKit.Entity>", isOptional: false),
                Property(name: "gain", swiftType: "Swift.Double", isOptional: false),
                Property(name: "isPlaying", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "resources", swiftType: "Swift.Array<RealityKit.AudioResource>", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_break_audio_mix_group": NodeSchema(
            module: "RealityKit", typeName: "AudioMixGroup", properties: [
                Property(name: "gain", swiftType: "Swift.Double", isOptional: false),
                Property(name: "isMuted", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "name", swiftType: "Swift.String", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_break_audio_playback_controller": NodeSchema(
            module: "RealityKit", typeName: "AudioPlaybackController", properties: [
                Property(name: "entity", swiftType: "RealityKit.Entity", isOptional: true),
                Property(name: "gain", swiftType: "Swift.Double", isOptional: false),
                Property(name: "isPlaying", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "resource", swiftType: "RealityKit.AudioResource", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_break_cgpoint": NodeSchema(
            module: "CoreGraphics", typeName: "CGPoint", properties: [
                Property(name: "x", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "y", swiftType: "CoreGraphics.CGFloat", isOptional: false),
            ]
        ),
        "tm_break_cgsize": NodeSchema(
            module: "CoreGraphics", typeName: "CGSize", properties: [
                Property(name: "height", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "width", swiftType: "CoreGraphics.CGFloat", isOptional: false),
            ]
        ),
        "tm_break_collision_filter": NodeSchema(
            module: "RealityKit", typeName: "CollisionFilter", properties: [
                Property(name: "group", swiftType: "RealityKit.CollisionGroup", isOptional: false),
                Property(name: "mask", swiftType: "RealityKit.CollisionGroup", isOptional: false),
            ]
        ),
        "tm_break_contact": NodeSchema(
            module: "RealityKit", typeName: "Contact", properties: [
                Property(name: "impulse", swiftType: "Swift.Float", isOptional: false),
                Property(name: "normal", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "point", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_break_edge_insets": NodeSchema(
            module: "Foundation", typeName: "EdgeInsets", properties: [
                Property(name: "bottom", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "left", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "right", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "top", swiftType: "CoreGraphics.CGFloat", isOptional: false),
            ]
        ),
        "tm_break_entity": NodeSchema(
            module: "RealityKit", typeName: "Entity", properties: [
                Property(name: "availableAnimations", swiftType: "Swift.Array<RealityKit.AnimationResource>", isOptional: false),
                Property(name: "characterController", swiftType: "RealityFoundation.CharacterControllerComponent", isOptional: true),
                Property(name: "characterControllerState", swiftType: "RealityFoundation.CharacterControllerStateComponent", isOptional: true),
                Property(name: "children", swiftType: "RealityKit.Entity.ChildCollection", isOptional: false),
                Property(name: "components", swiftType: "RealityKit.Entity.ComponentSet", isOptional: false),
                Property(name: "debugDescription", swiftType: "Swift.String", isOptional: false),
                Property(name: "id", swiftType: "Swift.UInt64", isOptional: false),
                Property(name: "isAccessibilityElement", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isActive", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isAnchored", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isEnabled", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isEnabledInHierarchy", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isOwner", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "localForward", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "localRight", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "localUp", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "name", swiftType: "Swift.String", isOptional: false),
                Property(name: "orientation", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "parent", swiftType: "RealityKit.Entity", isOptional: true),
                Property(name: "position", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "scale", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "scene", swiftType: "RealityKit.Scene", isOptional: true),
                Property(name: "transform", swiftType: "RealityKit.Transform", isOptional: false),
                Property(name: "transformMatrix", swiftType: "__C.simd_float4x4", isOptional: false),
                Property(name: "worldForward", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "worldOrientation", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "worldPosition", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "worldRight", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "worldScale", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "worldTransform", swiftType: "RealityKit.Transform", isOptional: false),
                Property(name: "worldTransformMatrix", swiftType: "__C.simd_float4x4", isOptional: false),
                Property(name: "worldUp", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_break_matrix2x2": NodeSchema(
            module: "Math3D", typeName: "Matrix2x2", properties: [
                Property(name: "col0", swiftType: "Swift.SIMD2<Swift.Float>", isOptional: false),
                Property(name: "col1", swiftType: "Swift.SIMD2<Swift.Float>", isOptional: false),
                Property(name: "determinant", swiftType: "Swift.Float", isOptional: false),
                Property(name: "inverse", swiftType: "__C.simd_float2x2", isOptional: false),
                Property(name: "transpose", swiftType: "__C.simd_float2x2", isOptional: false),
            ]
        ),
        "tm_break_matrix3x3": NodeSchema(
            module: "Math3D", typeName: "Matrix3x3", properties: [
                Property(name: "col0", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "col1", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "col2", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "determinant", swiftType: "Swift.Float", isOptional: false),
                Property(name: "inverse", swiftType: "__C.simd_float3x3", isOptional: false),
                Property(name: "transpose", swiftType: "__C.simd_float3x3", isOptional: false),
            ]
        ),
        "tm_break_matrix4x4": NodeSchema(
            module: "Math3D", typeName: "Matrix4x4", properties: [
                Property(name: "col0", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "col1", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "col2", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "col3", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "determinant", swiftType: "Swift.Float", isOptional: false),
                Property(name: "inverse", swiftType: "__C.simd_float4x4", isOptional: false),
                Property(name: "rotation", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "scale", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "translation", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "transpose", swiftType: "__C.simd_float4x4", isOptional: false),
            ]
        ),
        "tm_break_quaternion": NodeSchema(
            module: "Math3D", typeName: "Quaternion", properties: [
                Property(name: "angle", swiftType: "Swift.Float", isOptional: false),
                Property(name: "axis", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "conjugate", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "imag", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "inverse", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "length", swiftType: "Swift.Float", isOptional: false),
                Property(name: "real", swiftType: "Swift.Float", isOptional: false),
                Property(name: "vector", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_break_scene": NodeSchema(
            module: "RealityKit", typeName: "Scene", properties: [
                Property(name: "hashValue", swiftType: "Swift.Int", isOptional: false),
                Property(name: "id", swiftType: "Swift.UInt64", isOptional: false),
                Property(name: "name", swiftType: "Swift.String", isOptional: false),
            ]
        ),
        "tm_break_vector2": NodeSchema(
            module: "Math3D", typeName: "Vector2", properties: [
                Property(name: "x", swiftType: "Swift.Float", isOptional: false),
                Property(name: "y", swiftType: "Swift.Float", isOptional: false),
            ]
        ),
        "tm_break_vector3": NodeSchema(
            module: "Math3D", typeName: "Vector3", properties: [
                Property(name: "x", swiftType: "Swift.Float", isOptional: false),
                Property(name: "xy", swiftType: "Swift.SIMD2<Swift.Float>", isOptional: false),
                Property(name: "y", swiftType: "Swift.Float", isOptional: false),
                Property(name: "z", swiftType: "Swift.Float", isOptional: false),
            ]
        ),
        "tm_break_vector4": NodeSchema(
            module: "Math3D", typeName: "Vector4", properties: [
                Property(name: "w", swiftType: "Swift.Float", isOptional: false),
                Property(name: "x", swiftType: "Swift.Float", isOptional: false),
                Property(name: "xyz", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "y", swiftType: "Swift.Float", isOptional: false),
                Property(name: "z", swiftType: "Swift.Float", isOptional: false),
            ]
        ),
    ]

    public static let writeNodes: [String: NodeSchema] = [
        "tm_write_animation_playback_controller": NodeSchema(
            module: "RealityKit", typeName: "AnimationPlaybackController", properties: [
                Property(name: "blendFactor", swiftType: "Swift.Float", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Float", isOptional: false),
                Property(name: "time", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_write_audio_group_playback_controller": NodeSchema(
            module: "RealityKit", typeName: "AudioPlaybackGroupController", properties: [
                Property(name: "gain", swiftType: "Swift.Double", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_write_audio_mix_group": NodeSchema(
            module: "RealityKit", typeName: "AudioMixGroup", properties: [
                Property(name: "gain", swiftType: "Swift.Double", isOptional: false),
                Property(name: "isMuted", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_write_audio_playback_controller": NodeSchema(
            module: "RealityKit", typeName: "AudioPlaybackController", properties: [
                Property(name: "gain", swiftType: "Swift.Double", isOptional: false),
                Property(name: "speed", swiftType: "Swift.Double", isOptional: false),
            ]
        ),
        "tm_write_cgpoint": NodeSchema(
            module: "CoreGraphics", typeName: "CGPoint", properties: [
                Property(name: "x", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "y", swiftType: "CoreGraphics.CGFloat", isOptional: false),
            ]
        ),
        "tm_write_cgsize": NodeSchema(
            module: "CoreGraphics", typeName: "CGSize", properties: [
                Property(name: "height", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "width", swiftType: "CoreGraphics.CGFloat", isOptional: false),
            ]
        ),
        "tm_write_collision_filter": NodeSchema(
            module: "RealityKit", typeName: "CollisionFilter", properties: [
                Property(name: "group", swiftType: "RealityKit.CollisionGroup", isOptional: false),
                Property(name: "mask", swiftType: "RealityKit.CollisionGroup", isOptional: false),
            ]
        ),
        "tm_write_edge_insets": NodeSchema(
            module: "Foundation", typeName: "EdgeInsets", properties: [
                Property(name: "bottom", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "left", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "right", swiftType: "CoreGraphics.CGFloat", isOptional: false),
                Property(name: "top", swiftType: "CoreGraphics.CGFloat", isOptional: false),
            ]
        ),
        "tm_write_entity": NodeSchema(
            module: "RealityKit", typeName: "Entity", properties: [
                Property(name: "characterController", swiftType: "RealityFoundation.CharacterControllerComponent", isOptional: true),
                Property(name: "characterControllerState", swiftType: "RealityFoundation.CharacterControllerStateComponent", isOptional: true),
                Property(name: "components", swiftType: "RealityKit.Entity.ComponentSet", isOptional: false),
                Property(name: "isAccessibilityElement", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "isEnabled", swiftType: "Swift.Bool", isOptional: false),
                Property(name: "name", swiftType: "Swift.String", isOptional: false),
                Property(name: "orientation", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "position", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "scale", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "transform", swiftType: "RealityKit.Transform", isOptional: false),
                Property(name: "transformMatrix", swiftType: "__C.simd_float4x4", isOptional: false),
                Property(name: "worldOrientation", swiftType: "__C.simd_quatf", isOptional: false),
                Property(name: "worldPosition", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "worldScale", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "worldTransform", swiftType: "RealityKit.Transform", isOptional: false),
                Property(name: "worldTransformMatrix", swiftType: "__C.simd_float4x4", isOptional: false),
            ]
        ),
        "tm_write_matrix2x2": NodeSchema(
            module: "Math3D", typeName: "Matrix2x2", properties: [
                Property(name: "col0", swiftType: "Swift.SIMD2<Swift.Float>", isOptional: false),
                Property(name: "col1", swiftType: "Swift.SIMD2<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_write_matrix3x3": NodeSchema(
            module: "Math3D", typeName: "Matrix3x3", properties: [
                Property(name: "col0", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "col1", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "col2", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_write_matrix4x4": NodeSchema(
            module: "Math3D", typeName: "Matrix4x4", properties: [
                Property(name: "col0", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "col1", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "col2", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
                Property(name: "col3", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_write_quaternion": NodeSchema(
            module: "Math3D", typeName: "Quaternion", properties: [
                Property(name: "imag", swiftType: "Swift.SIMD3<Swift.Float>", isOptional: false),
                Property(name: "real", swiftType: "Swift.Float", isOptional: false),
                Property(name: "vector", swiftType: "Swift.SIMD4<Swift.Float>", isOptional: false),
            ]
        ),
        "tm_write_vector2": NodeSchema(
            module: "Math3D", typeName: "Vector2", properties: [
                Property(name: "x", swiftType: "Swift.Float", isOptional: false),
                Property(name: "y", swiftType: "Swift.Float", isOptional: false),
            ]
        ),
        "tm_write_vector3": NodeSchema(
            module: "Math3D", typeName: "Vector3", properties: [
                Property(name: "x", swiftType: "Swift.Float", isOptional: false),
                Property(name: "y", swiftType: "Swift.Float", isOptional: false),
                Property(name: "z", swiftType: "Swift.Float", isOptional: false),
            ]
        ),
        "tm_write_vector4": NodeSchema(
            module: "Math3D", typeName: "Vector4", properties: [
                Property(name: "w", swiftType: "Swift.Float", isOptional: false),
                Property(name: "x", swiftType: "Swift.Float", isOptional: false),
                Property(name: "y", swiftType: "Swift.Float", isOptional: false),
                Property(name: "z", swiftType: "Swift.Float", isOptional: false),
            ]
        ),
    ]

    public static let enumMakeNodes: [String: EnumNodeSchema] = [
        "tm_make_anchoring_component_physics_simulation": EnumNodeSchema(
            module: "RealityKit", typeName: "AnchoringComponent.PhysicsSimulation", cases: [
                EnumCase(name: "isolated", associatedValues: [
                ]),
                EnumCase(name: "none", associatedValues: [
                ]),
            ]
        ),
        "tm_make_anchoring_component_target": EnumNodeSchema(
            module: "RealityKit", typeName: "AnchoringComponent.Target", cases: [
                EnumCase(name: "anchor", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Foundation.UUID"),
                ]),
                EnumCase(name: "body", associatedValues: [
                ]),
                EnumCase(name: "camera", associatedValues: [
                ]),
                EnumCase(name: "face", associatedValues: [
                ]),
                EnumCase(name: "image", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.String"),
                    EnumAssociatedValue(name: "value1", swiftType: "Swift.String"),
                ]),
                EnumCase(name: "object", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.String"),
                    EnumAssociatedValue(name: "value1", swiftType: "Swift.String"),
                ]),
                EnumCase(name: "plane", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityKit.AnchoringComponent.Target.Alignment"),
                    EnumAssociatedValue(name: "value1", swiftType: "RealityKit.AnchoringComponent.Target.Classification"),
                    EnumAssociatedValue(name: "value2", swiftType: "Swift.SIMD2<Swift.Float>"),
                ]),
                EnumCase(name: "referenceImage", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "(extension in RealityFoundation):RealityKit.AnchoringComponent.ImageAnchoringSource"),
                ]),
                EnumCase(name: "referenceObject", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "(extension in RealityFoundation):RealityKit.AnchoringComponent.ObjectAnchoringSource"),
                ]),
                EnumCase(name: "world", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float4x4"),
                ]),
            ]
        ),
        "tm_make_anchoring_component_target_alignment": EnumNodeSchema(
            module: "RealityKit", typeName: "AnchoringComponent.Target.Alignment", cases: [
                EnumCase(name: "any", associatedValues: [
                ]),
                EnumCase(name: "horizontal", associatedValues: [
                ]),
                EnumCase(name: "vertical", associatedValues: [
                ]),
            ]
        ),
        "tm_make_anchoring_component_target_classification": EnumNodeSchema(
            module: "RealityKit", typeName: "AnchoringComponent.Target.Classification", cases: [
                EnumCase(name: "any", associatedValues: [
                ]),
                EnumCase(name: "ceiling", associatedValues: [
                ]),
                EnumCase(name: "floor", associatedValues: [
                ]),
                EnumCase(name: "seat", associatedValues: [
                ]),
                EnumCase(name: "table", associatedValues: [
                ]),
                EnumCase(name: "wall", associatedValues: [
                ]),
            ]
        ),
        "tm_make_anchoring_component_tracking_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "AnchoringComponent.TrackingMode", cases: [
                EnumCase(name: "continuous", associatedValues: [
                ]),
                EnumCase(name: "once", associatedValues: [
                ]),
                EnumCase(name: "predicted", associatedValues: [
                ]),
            ]
        ),
        "tm_make_animation_timing_function": EnumNodeSchema(
            module: "RealityKit", typeName: "AnimationTimingFunction", cases: [
                EnumCase(name: "default", associatedValues: [
                ]),
                EnumCase(name: "easeIn", associatedValues: [
                ]),
                EnumCase(name: "easeInOut", associatedValues: [
                ]),
                EnumCase(name: "easeOut", associatedValues: [
                ]),
                EnumCase(name: "linear", associatedValues: [
                ]),
            ]
        ),
        "tm_make_audio_directivity": EnumNodeSchema(
            module: "RealityKit", typeName: "Audio.Directivity", cases: [
                EnumCase(name: "beam", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Double"),
                ]),
            ]
        ),
        "tm_make_audio_distance_attenuation": EnumNodeSchema(
            module: "RealityKit", typeName: "Audio.DistanceAttenuation", cases: [
                EnumCase(name: "rolloff", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Double"),
                ]),
            ]
        ),
        "tm_make_audio_file_resource_loading_strategy": EnumNodeSchema(
            module: "RealityKit", typeName: "AudioFileResource.LoadingStrategy", cases: [
                EnumCase(name: "preload", associatedValues: [
                ]),
                EnumCase(name: "stream", associatedValues: [
                ]),
            ]
        ),
        "tm_make_audio_resource_normalization": EnumNodeSchema(
            module: "RealityKit", typeName: "AudioResource.Normalization", cases: [
                EnumCase(name: "dynamic", associatedValues: [
                ]),
            ]
        ),
        "tm_make_character_controller_component_collision_flags": EnumNodeSchema(
            module: "RealityKit", typeName: "CharacterControllerComponent.CollisionFlags", cases: [
                EnumCase(name: "bottom", associatedValues: [
                ]),
                EnumCase(name: "none", associatedValues: [
                ]),
                EnumCase(name: "side", associatedValues: [
                ]),
                EnumCase(name: "top", associatedValues: [
                ]),
            ]
        ),
        "tm_make_collision_cast_query_type": EnumNodeSchema(
            module: "RealityKit", typeName: "CollisionCastQueryType", cases: [
                EnumCase(name: "all", associatedValues: [
                ]),
                EnumCase(name: "any", associatedValues: [
                ]),
                EnumCase(name: "nearest", associatedValues: [
                ]),
            ]
        ),
        "tm_make_collision_component_collision_options": EnumNodeSchema(
            module: "RealityKit", typeName: "CollisionComponent.CollisionOptions", cases: [
                EnumCase(name: "fullContactInformation", associatedValues: [
                ]),
                EnumCase(name: "none", associatedValues: [
                ]),
                EnumCase(name: "static", associatedValues: [
                ]),
            ]
        ),
        "tm_make_collision_component_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "CollisionComponent.Mode", cases: [
                EnumCase(name: "colliding", associatedValues: [
                ]),
                EnumCase(name: "default", associatedValues: [
                ]),
                EnumCase(name: "trigger", associatedValues: [
                ]),
            ]
        ),
        "tm_make_collision_group": EnumNodeSchema(
            module: "RealityKit", typeName: "CollisionGroup", cases: [
                EnumCase(name: "all", associatedValues: [
                ]),
                EnumCase(name: "default", associatedValues: [
                ]),
                EnumCase(name: "sceneUnderstanding", associatedValues: [
                ]),
            ]
        ),
        "tm_make_directional_light_component_shadow_shadow_projection_type": EnumNodeSchema(
            module: "RealityKit", typeName: "DirectionalLightComponent.Shadow.ShadowProjectionType", cases: [
                EnumCase(name: "automatic", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
                EnumCase(name: "fixed", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                    EnumAssociatedValue(name: "value1", swiftType: "Swift.Float"),
                    EnumAssociatedValue(name: "value2", swiftType: "Swift.Float"),
                ]),
            ]
        ),
        "tm_make_entity_forward_direction": EnumNodeSchema(
            module: "RealityKit", typeName: "Entity.ForwardDirection", cases: [
                EnumCase(name: "negativeZ", associatedValues: [
                ]),
                EnumCase(name: "positiveZ", associatedValues: [
                ]),
            ]
        ),
        "tm_make_font_weight": EnumNodeSchema(
            module: "Foundation", typeName: "Font.Weight", cases: [
                EnumCase(name: "black", associatedValues: [
                ]),
                EnumCase(name: "bold", associatedValues: [
                ]),
                EnumCase(name: "heavy", associatedValues: [
                ]),
                EnumCase(name: "light", associatedValues: [
                ]),
                EnumCase(name: "medium", associatedValues: [
                ]),
                EnumCase(name: "regular", associatedValues: [
                ]),
                EnumCase(name: "semibold", associatedValues: [
                ]),
                EnumCase(name: "thin", associatedValues: [
                ]),
                EnumCase(name: "ultraLight", associatedValues: [
                ]),
            ]
        ),
        "tm_make_hover_effect_component_opacity_function": EnumNodeSchema(
            module: "RealityKit", typeName: "HoverEffectComponent.OpacityFunction", cases: [
                EnumCase(name: "blend", associatedValues: [
                ]),
                EnumCase(name: "full", associatedValues: [
                ]),
                EnumCase(name: "mask", associatedValues: [
                ]),
            ]
        ),
        "tm_make_input_target_component_input_type": EnumNodeSchema(
            module: "RealityKit", typeName: "InputTargetComponent.InputType", cases: [
                EnumCase(name: "all", associatedValues: [
                ]),
                EnumCase(name: "direct", associatedValues: [
                ]),
                EnumCase(name: "indirect", associatedValues: [
                ]),
            ]
        ),
        "tm_make_material_parameter_types_blend_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialParameterTypes.BlendMode", cases: [
                EnumCase(name: "add", associatedValues: [
                ]),
                EnumCase(name: "alpha", associatedValues: [
                ]),
            ]
        ),
        "tm_make_material_parameter_types_face_culling": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialParameterTypes.FaceCulling", cases: [
                EnumCase(name: "back", associatedValues: [
                ]),
                EnumCase(name: "front", associatedValues: [
                ]),
                EnumCase(name: "none", associatedValues: [
                ]),
            ]
        ),
        "tm_make_material_parameter_types_triangle_fill_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialParameterTypes.TriangleFillMode", cases: [
                EnumCase(name: "fill", associatedValues: [
                ]),
                EnumCase(name: "lines", associatedValues: [
                ]),
            ]
        ),
        "tm_make_material_parameters_value": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialParameters.Value", cases: [
                EnumCase(name: "bool", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Bool"),
                ]),
                EnumCase(name: "color", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.CGColorRef"),
                ]),
                EnumCase(name: "float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
                EnumCase(name: "float2x2", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float2x2"),
                ]),
                EnumCase(name: "float3x3", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float3x3"),
                ]),
                EnumCase(name: "float4x4", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float4x4"),
                ]),
                EnumCase(name: "int", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Int32"),
                ]),
                EnumCase(name: "simd2Float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.SIMD2<Swift.Float>"),
                ]),
                EnumCase(name: "simd3Float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.SIMD3<Swift.Float>"),
                ]),
                EnumCase(name: "simd4Float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.SIMD4<Swift.Float>"),
                ]),
                EnumCase(name: "texture", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.MaterialParameters.Texture"),
                ]),
                EnumCase(name: "textureResource", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityKit.TextureResource"),
                ]),
            ]
        ),
        "tm_make_material_scalar_parameter": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialScalarParameter", cases: [
                EnumCase(name: "float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
            ]
        ),
        "tm_make_physically_based_material_blending": EnumNodeSchema(
            module: "RealityKit", typeName: "PhysicallyBasedMaterial.Blending", cases: [
                EnumCase(name: "opaque", associatedValues: [
                ]),
                EnumCase(name: "transparent", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.PhysicallyBasedMaterial.Opacity"),
                ]),
            ]
        ),
        "tm_make_physics_body_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "PhysicsBodyMode", cases: [
                EnumCase(name: "dynamic", associatedValues: [
                ]),
                EnumCase(name: "kinematic", associatedValues: [
                ]),
                EnumCase(name: "static", associatedValues: [
                ]),
            ]
        ),
        "tm_make_physics_simulation_component_collision_options": EnumNodeSchema(
            module: "RealityKit", typeName: "PhysicsSimulationComponent.CollisionOptions", cases: [
                EnumCase(name: "all", associatedValues: [
                ]),
                EnumCase(name: "none", associatedValues: [
                ]),
                EnumCase(name: "reportKinematicVsKinematic", associatedValues: [
                ]),
                EnumCase(name: "reportKinematicVsStatic", associatedValues: [
                ]),
            ]
        ),
        "tm_make_portal_component_clipping_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "PortalComponent.ClippingMode", cases: [
                EnumCase(name: "disabled", associatedValues: [
                ]),
                EnumCase(name: "plane", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.PortalComponent.Plane"),
                ]),
            ]
        ),
        "tm_make_portal_component_crossing_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "PortalComponent.CrossingMode", cases: [
                EnumCase(name: "disabled", associatedValues: [
                ]),
                EnumCase(name: "plane", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.PortalComponent.Plane"),
                ]),
            ]
        ),
        "tm_make_portal_component_options": EnumNodeSchema(
            module: "RealityKit", typeName: "PortalComponent.Options", cases: [
                EnumCase(name: "allowCrossing", associatedValues: [
                ]),
                EnumCase(name: "clipContents", associatedValues: [
                ]),
            ]
        ),
        "tm_make_reverb": EnumNodeSchema(
            module: "RealityKit", typeName: "Reverb", cases: [
                EnumCase(name: "anechoic", associatedValues: [
                ]),
                EnumCase(name: "concertHall", associatedValues: [
                ]),
                EnumCase(name: "largeRoom", associatedValues: [
                ]),
                EnumCase(name: "largeRoomTreated", associatedValues: [
                ]),
                EnumCase(name: "mediumRoomDry", associatedValues: [
                ]),
                EnumCase(name: "mediumRoomTreated", associatedValues: [
                ]),
                EnumCase(name: "outside", associatedValues: [
                ]),
                EnumCase(name: "smallRoom", associatedValues: [
                ]),
                EnumCase(name: "smallRoomBright", associatedValues: [
                ]),
                EnumCase(name: "veryLargeRoom", associatedValues: [
                ]),
                EnumCase(name: "verySmallRoomBright", associatedValues: [
                ]),
            ]
        ),
        "tm_make_spot_light_component_shadow_shadow_clipping_plane": EnumNodeSchema(
            module: "RealityKit", typeName: "SpotLightComponent.Shadow.ShadowClippingPlane", cases: [
                EnumCase(name: "automatic", associatedValues: [
                ]),
                EnumCase(name: "fixed", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
            ]
        ),
        "tm_make_text_alignment": EnumNodeSchema(
            module: "Foundation", typeName: "TextAlignment", cases: [
                EnumCase(name: "center", associatedValues: [
                ]),
                EnumCase(name: "justified", associatedValues: [
                ]),
                EnumCase(name: "left", associatedValues: [
                ]),
                EnumCase(name: "natural", associatedValues: [
                ]),
                EnumCase(name: "right", associatedValues: [
                ]),
            ]
        ),
    ]

    public static let enumBreakNodes: [String: EnumNodeSchema] = [
        "tm_break_anchoring_component_target": EnumNodeSchema(
            module: "RealityKit", typeName: "AnchoringComponent.Target", cases: [
                EnumCase(name: "anchor", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Foundation.UUID"),
                ]),
                EnumCase(name: "body", associatedValues: [
                ]),
                EnumCase(name: "camera", associatedValues: [
                ]),
                EnumCase(name: "face", associatedValues: [
                ]),
                EnumCase(name: "image", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.String"),
                    EnumAssociatedValue(name: "value1", swiftType: "Swift.String"),
                ]),
                EnumCase(name: "object", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.String"),
                    EnumAssociatedValue(name: "value1", swiftType: "Swift.String"),
                ]),
                EnumCase(name: "plane", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityKit.AnchoringComponent.Target.Alignment"),
                    EnumAssociatedValue(name: "value1", swiftType: "RealityKit.AnchoringComponent.Target.Classification"),
                    EnumAssociatedValue(name: "value2", swiftType: "Swift.SIMD2<Swift.Float>"),
                ]),
                EnumCase(name: "referenceImage", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "(extension in RealityFoundation):RealityKit.AnchoringComponent.ImageAnchoringSource"),
                ]),
                EnumCase(name: "referenceObject", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "(extension in RealityFoundation):RealityKit.AnchoringComponent.ObjectAnchoringSource"),
                ]),
                EnumCase(name: "world", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float4x4"),
                ]),
            ]
        ),
        "tm_break_audio_directivity": EnumNodeSchema(
            module: "RealityKit", typeName: "Audio.Directivity", cases: [
                EnumCase(name: "beam", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Double"),
                ]),
            ]
        ),
        "tm_break_audio_distance_attenuation": EnumNodeSchema(
            module: "RealityKit", typeName: "Audio.DistanceAttenuation", cases: [
                EnumCase(name: "rolloff", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Double"),
                ]),
            ]
        ),
        "tm_break_collision_group_number": EnumNodeSchema(
            module: "RealityKit", typeName: "CollisionGroup", cases: [
                EnumCase(name: "all", associatedValues: [
                ]),
                EnumCase(name: "default", associatedValues: [
                ]),
                EnumCase(name: "sceneUnderstanding", associatedValues: [
                ]),
            ]
        ),
        "tm_break_directional_light_component_shadow_shadow_projection_type": EnumNodeSchema(
            module: "RealityKit", typeName: "DirectionalLightComponent.Shadow.ShadowProjectionType", cases: [
                EnumCase(name: "automatic", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
                EnumCase(name: "fixed", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                    EnumAssociatedValue(name: "value1", swiftType: "Swift.Float"),
                    EnumAssociatedValue(name: "value2", swiftType: "Swift.Float"),
                ]),
            ]
        ),
        "tm_break_material_parameters_value": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialParameters.Value", cases: [
                EnumCase(name: "bool", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Bool"),
                ]),
                EnumCase(name: "color", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.CGColorRef"),
                ]),
                EnumCase(name: "float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
                EnumCase(name: "float2x2", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float2x2"),
                ]),
                EnumCase(name: "float3x3", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float3x3"),
                ]),
                EnumCase(name: "float4x4", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "__C.simd_float4x4"),
                ]),
                EnumCase(name: "int", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Int32"),
                ]),
                EnumCase(name: "simd2Float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.SIMD2<Swift.Float>"),
                ]),
                EnumCase(name: "simd3Float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.SIMD3<Swift.Float>"),
                ]),
                EnumCase(name: "simd4Float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.SIMD4<Swift.Float>"),
                ]),
                EnumCase(name: "texture", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.MaterialParameters.Texture"),
                ]),
                EnumCase(name: "textureResource", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityKit.TextureResource"),
                ]),
            ]
        ),
        "tm_break_material_scalar_parameter": EnumNodeSchema(
            module: "RealityKit", typeName: "MaterialScalarParameter", cases: [
                EnumCase(name: "float", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
            ]
        ),
        "tm_break_physically_based_material_blending": EnumNodeSchema(
            module: "RealityKit", typeName: "PhysicallyBasedMaterial.Blending", cases: [
                EnumCase(name: "opaque", associatedValues: [
                ]),
                EnumCase(name: "transparent", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.PhysicallyBasedMaterial.Opacity"),
                ]),
            ]
        ),
        "tm_break_portal_component_clipping_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "PortalComponent.ClippingMode", cases: [
                EnumCase(name: "disabled", associatedValues: [
                ]),
                EnumCase(name: "plane", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.PortalComponent.Plane"),
                ]),
            ]
        ),
        "tm_break_portal_component_crossing_mode": EnumNodeSchema(
            module: "RealityKit", typeName: "PortalComponent.CrossingMode", cases: [
                EnumCase(name: "disabled", associatedValues: [
                ]),
                EnumCase(name: "plane", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "RealityFoundation.PortalComponent.Plane"),
                ]),
            ]
        ),
        "tm_break_spot_light_component_shadow_shadow_clipping_plane": EnumNodeSchema(
            module: "RealityKit", typeName: "SpotLightComponent.Shadow.ShadowClippingPlane", cases: [
                EnumCase(name: "automatic", associatedValues: [
                ]),
                EnumCase(name: "fixed", associatedValues: [
                    EnumAssociatedValue(name: "value0", swiftType: "Swift.Float"),
                ]),
            ]
        ),
    ]

}
